apiVersion: database.orange.data/v1alpha1
kind: PostgreSQLInstance
metadata:
name: {{base-name}}
namespace: {{namespace}}
spec:
compositionSelector:
  matchLabels:
  environment: {{env}}
  provider: provider-aws
parameters:
  allocatedStorage: 100
  dbInstanceClass: db.t3.medium
  dbName: {{env}}
  dbParameterGroupName: {{namespace}}-{{engine}}-secure
  engine: {{engine}}
  engineVersion: '12.5'
writeConnectionSecretToRef:
  name: {{base-name}}